# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Roku-RCP
version:      0.03
version_from: lib/Roku/RCP.pm
installdirs:  site
requires:
    IO::Socket:                    0
    IO::Socket::INET:              0
    Net::Cmd:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
